apiVersion: apps/v1
kind: Deployment
metadata:
  name: housing-publication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: housing-publication
  template:
    metadata:
      labels:
        app: housing-publication
    spec:
      containers:
        - image: cloudprojectantoninkylian/housing-publication:1.0.0
          imagePullPolicy: IfNotPresent
          name: housing-publication
      restartPolicy: Always
