apiVersion: v1
kind: Service
metadata:
  labels:
    app: housing-publication
  name: housing-publication
spec:
  ports:
    - nodePort: 30945
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: housing-publication
  type: LoadBalancer
